void getDegreeOperation(const ArrayBag<Polynomial>& polynomials);
void getPolynomialIndex(int& polyTarget, const ArrayBag<Polynomial>& polynomials);
void sumOperations(ArrayBag<Polynomial>& polynomials);
void printOperations(const ArrayBag<Polynomial>& polynomials);
void sortOperations(bool& polynomialsAreSorted, ArrayBag<Polynomial>& polynomials);
void displayCoefficientOperations(ArrayBag<Polynomial>& polynomials);
void changeCoefficientOperations(ArrayBag<Polynomial>& polynomials);
void removeOperations(ArrayBag<Polynomial>& polynomials);
void newPolynomialOperations(ArrayBag<Polynomial>& polynomials);
void getTermQuantityOperations(ArrayBag<Polynomial>& polynomials);
void getPolynomialQuantityOperations(ArrayBag<Polynomial>& polynomials);
void increaseCoefficientOperations(ArrayBag<Polynomial>& polynomials);
void highestPowerCoefficientOperations(ArrayBag<Polynomial>& polynomials);
void removeTermOperations(ArrayBag<Polynomial>& polynomials);
void allPolynomialsDegreeOperations(ArrayBag<Polynomial>& polynomials);